sudo: required

language: node_js 

services:
  - docker

before_install:
  - docker build -t dgaspe/studis-vue .

dist: trusty

deploy:
  provider: script
  script: bash docker_push
  on:
    branch: master 
