sudo: required

language: bash 
services:
  - docker

before_script:
  - docker build -t dgaspe/studis-vue .

dist: trusty

deploy:
  provider: script
  script: bash docker_push
  on:
    branch: master 
