<template>
  <div>
    <b-form @submit="onSubmit" @reset="onReset" v-if="true">
      <h3>Izpolni vpisni list</h3>
      <b-form-group id="exampleInputGroup1"
                    label="Name:"
                    label-for="exampleInput1">
        <b-form-input id="exampleInput1"
                      type="email"
                      required>
        </b-form-input>
      </b-form-group>
      <b-form-group id="exampleInputGroup2"
                    label="Surname:"
                    label-for="exampleInput2">
        <b-form-input id="exampleInput2"
                      type="text"
                      required>
        </b-form-input>
        
      </b-form-group>
       <b-form-group id="exampleInputGroup2"
                    label="Date of birth:"
                    label-for="exampleInput2">
        <b-form-input id="exampleInput2"
                      type="date"
                      required>
        </b-form-input>
        
      </b-form-group>
      <b-form-group id="exampleInputGroup2"
                    label="Country:"
                    label-for="exampleInput2">
        <b-form-select v-model="selectedCountry" :options="countries" class="mb-3">
        </b-form-select>
      </b-form-group>
      
    
      <b-form-group id="exampleInputGroup2"
                    label="Tax number:"
                    label-for="exampleInput2">
        <b-form-input id="exampleInput2"
                      type="text" 
                      pattern="\d*" 
                      maxlength="8"
                      required>
        </b-form-input>
        
      </b-form-group>
      <b-form-group id="exampleInputGroup2"
                    label="Post number:"
                    label-for="exampleInput2">
        <b-form-input id="exampleInput2"
                      type="text" 
                      pattern="\d*" 
                      maxlength="4"
                      required>
        </b-form-input>
        
      </b-form-group>
      <b-form-group id="exampleInputGroup2"
                    label="Občina:"
                    label-for="exampleInput2">
        <b-form-select v-model="selectedPost" :options="posts" class="mb-3">
        </b-form-select>
        
      </b-form-group>

      <b-button type="submit" variant="primary" @click.prevent="saveProfile">Shrani</b-button>
      <b-button type="reset" variant="danger" @click.prevent="goHome">Nazaj</b-button>
    </b-form>
  </div>
</template>

<script lang="ts">
import { Component, Vue } from 'vue-property-decorator';

@Component({
  name: 'forgotPassword',
  data () {
    return {
      selectedCountry: '',
      selectedPost: '',
      countries: [
        { value: 'Afganistan', text: 'Afganistan' },
        { value: 'Alandski otoki', text: 'Alandski otoki' },
        { value: 'Albanija', text: 'Albanija' },
        { value: 'Alžirija', text: 'Alžirija' },
        { value: 'Ameriška Samoa', text: 'Ameriška Samoa' },
        { value: 'Andora', text: 'Andora' },
        { value: 'Angola', text: 'Angola' },
        { value: 'Angvila', text: 'Angvila' },
        { value: 'Antarktika', text: 'Antarktika' },
        { value: 'Antigva in Barbuda', text: 'Antigva in Barbuda' },
        { value: 'Argenitna', text: 'Argenitna' },
        { value: 'Armenija', text: 'Armenija' },
        { value: 'Aruba', text: 'Aruba' },
        { value: 'Avstralija', text: 'Avstralija' },
        { value: 'Avstrija', text: 'Avstrija' },
        { value: 'Azerbajdžan', text: 'Azerbajdžan' },
        { value: 'Bahami', text: 'Bahami' },
        { value: 'Bahrajn', text: 'Bahrajn' },
        { value: 'Bangladeš', text: 'Bangladeš' },
        { value: 'Barbados', text: 'Barbados' },
        { value: 'Belorusija', text: 'Belorusija' },
        { value: 'Belgija', text: 'Belgija' },
        { value: 'Belize', text: 'Belize' },
        { value: 'Benin', text: 'Benin' },
        { value: 'Bermudi', text: 'Bermudi' },
        { value: 'Butan', text: 'Butan' },
        { value: 'Bolivija', text: 'Bolivija' },
        { value: 'Otočje Bonaire, Sv. Eustatij in Saba', text: 'Otočje Bonaire, Sv. Eustatij in Saba' },
        { value: 'Bosna in Hercegovina', text: 'Bosna in Hercegovina' },
        { value: 'Bocvana', text: 'Bocvana' },
        { value: 'Bouvetov otok', text: 'Bouvetov otok' },
        { value: 'Brazilija', text: 'Brazilija' },
        { value: 'Britansko ozemlje v Indijskem oceanu', text: 'Britansko ozemlje v Indijskem oceanu' },
        { value: 'Brunej', text: 'Brunej' },
        { value: 'Bolgarija', text: 'Bolgarija' },
        { value: 'Burkina Faso', text: 'Burkina Faso' },
        { value: 'Burundi ', text: 'Burundi ' },
        { value: 'Kambodža', text: 'Kambodža' },
        { value: 'Kamerun', text: 'Kamerun' },
        { value: 'Kanada', text: 'Kanada' },
        { value: 'Kapverdski otoki (Zelenortski otoki)', text: 'Kapverdski otoki (Zelenortski otoki)' },
        { value: 'Kajmanski otoki', text: 'Kajmanski otoki' },
        { value: 'Srednjeafriška republika', text: 'Srednjeafriška republika' },
        { value: 'Čad', text: 'Čad' },
        { value: 'Čile', text: 'Čile' },
        { value: 'Kitajska', text: 'Kitajska' },
        { value: 'Božični otok', text: 'Božični otok' },
        { value: 'Kokosovi in Keelingovi otoki', text: 'Kokosovi in Keelingovi otoki' },
        { value: 'Kolumbija', text: 'Kolumbija' },
        { value: 'Komori', text: 'Komori' },
        { value: 'Kongo', text: 'Kongo' },
        { value: 'Demokratična republika Kongo', text: 'Demokratična republika Kongo' },
        { value: 'Cookovi otoki', text: 'Cookovi otoki' },
        { value: 'Kostarika', text: 'Kostarika' },
        { value: 'Slonokoščena obala', text: 'Slonokoščena obala' },
        { value: 'Hrvaška', text: 'Hrvaška' },
        { value: 'Kuba', text: 'Kuba' },
        { value: 'Kurasao', text: 'Kurasao' },
        { value: 'Ciper', text: 'Ciper' },
        { value: 'Češka', text: 'Češka' },
        { value: 'Danska', text: 'Danska' },
        { value: 'Džibuti', text: 'Džibuti' },
        { value: 'Dominika', text: 'Dominika' },
        { value: 'Dominikanska republika', text: 'Dominikanska republika' },
        { value: 'Ekvador', text: 'Ekvador' },
        { value: 'Egipt', text: 'Egipt' },
        { value: 'Salvador', text: 'Salvador' },
        { value: 'Ekvatorialna Gvineja', text: 'Ekvatorialna Gvineja' },
        { value: 'Eritreja', text: 'Eritreja' },
        { value: 'Estonija', text: 'Estonija' },
        { value: 'Etiopija', text: 'Etiopija' },
        { value: 'Falkalndski otoki', text: 'Falkalndski otoki' },
        { value: 'Ferski otoki', text: 'Ferski otoki' },
        { value: 'Fidži', text: 'Fidži' },
        { value: 'Finska', text: 'Finska' },
        { value: 'Francija', text: 'Francija' },
        { value: 'Francoska Gvajana', text: 'Francoska Gvajana' },
        { value: 'Francoska Polinezija', text: 'Francoska Polinezija' },
        { value: 'Francoska južna ozemlja', text: 'Francoska južna ozemlja' },
        { value: 'Gabon', text: 'Gabon' },
        { value: 'Gambija', text: 'Gambija' },
        { value: 'Gruzija', text: 'Gruzija' },
        { value: 'Nemčija', text: 'Nemčija' },
        { value: 'Gana', text: 'Gana' },
        { value: 'Gibraltar', text: 'Gibraltar' },
        { value: 'Grčija', text: 'Grčija' },
        { value: 'Grenlandija', text: 'Grenlandija' },
        { value: 'Grenada', text: 'Grenada' },
        { value: 'Guadeloupe', text: 'Guadeloupe' },
        { value: 'Guam', text: 'Guam' },
        { value: 'Gvatemala', text: 'Gvatemala' },
        { value: 'Otok Guernsey', text: 'Otok Guernsey' },
        { value: 'Gvineja', text: 'Gvineja' },
        { value: 'Gvineja-Bissau', text: 'Gvineja-Bissau' },
        { value: 'Gvajana', text: 'Gvajana' },
        { value: 'Haiti', text: 'Haiti' },
        { value: 'Otok Heard in otočje McDonald', text: 'Otok Heard in otočje McDonald' },
        { value: 'Vatikan', text: 'Vatikan' },
        { value: 'Honduras', text: 'Honduras' },
        { value: 'Hong Kong', text: 'Hong Kong' },
        { value: 'Madžarska', text: 'Madžarska' },
        { value: 'Islandija', text: 'Islandija' },
        { value: 'Indija', text: 'Indija' },
        { value: 'Indonezija', text: 'Indonezija' },
        { value: 'Iran', text: 'Iran' },
        { value: 'Irak', text: 'Irak' },
        { value: 'Irska', text: 'Irska' },
        { value: 'Otok Man', text: 'Otok Man' },
        { value: 'Izrael', text: 'Izrael' },
        { value: 'Italija', text: 'Italija' },
        { value: 'Jamajka', text: 'Jamajka' },
        { value: 'Japonska', text: 'Japonska' },
        { value: 'Otok Jersey', text: 'Otok Jersey' },
        { value: 'Jordanija', text: 'Jordanija' },
        { value: 'Kazahstan', text: 'Kazahstan' },
        { value: 'Kenija', text: 'Kenija' },
        { value: 'Kiribati', text: 'Kiribati' },
        { value: 'Severna Koreja', text: 'Severna Koreja' },
        { value: 'Južna Koreja', text: 'Južna Koreja' },
        { value: 'Kuvajt', text: 'Kuvajt' },
        { value: 'Kirgizistan (Kirgizija)', text: 'Kirgizistan (Kirgizija)' },
        { value: 'Laos', text: 'Laos' },
        { value: 'Latvija', text: 'Latvija' },
        { value: 'Libanon', text: 'Libanon' },
        { value: 'Lesoto', text: 'Lesoto' },
        { value: 'Liberija', text: 'Liberija' },
        { value: 'Libija', text: 'Libija' },
        { value: 'Lihtenštajn', text: 'Lihtenštajn' },
        { value: 'Litva', text: 'Litva' },
        { value: 'Luksemburg', text: 'Luksemburg' },
        { value: 'Makao', text: 'Makao' },
        { value: 'Makedonija', text: 'Makedonija' },
        { value: 'Madagaskar', text: 'Madagaskar' },
        { value: 'Malavi', text: 'Malavi' },
        { value: 'Malezija', text: 'Malezija' },
        { value: 'Maldivi', text: 'Maldivi' },
        { value: 'Mali', text: 'Mali' },
        { value: 'Malta', text: 'Malta' },
        { value: 'Maršalovi otoki', text: 'Maršalovi otoki' },
        { value: 'Martinik', text: 'Martinik' },
        { value: 'Mavretanija', text: 'Mavretanija' },
        { value: 'Mauricius (Moris)', text: 'Mauricius (Moris)' },
        { value: 'Francoska skupnost Mejot', text: 'Francoska skupnost Mejot' },
        { value: 'Mehika', text: 'Mehika' },
        { value: 'Mikronezija', text: 'Mikronezija' },
        { value: 'Moldavija', text: 'Moldavija' },
        { value: 'Monako', text: 'Monako' },
        { value: 'Mongolija', text: 'Mongolija' },
        { value: 'Črna Gora', text: 'Črna Gora' },
        { value: 'Montserat', text: 'Montserat' },
        { value: 'Maroko', text: 'Maroko' },
        { value: 'Mozambik', text: 'Mozambik' },
        { value: 'Mjanmar', text: 'Mjanmar' },
        { value: 'Namibija', text: 'Namibija' },
        { value: 'Nauru', text: 'Nauru' },
        { value: 'Nepal', text: 'Nepal' },
        { value: 'Nizozemska', text: 'Nizozemska' },
        { value: 'Nova Kaledonija', text: 'Nova Kaledonija' },
        { value: 'Nova Zelandija', text: 'Nova Zelandija' },
        { value: 'Nikaragva', text: 'Nikaragva' },
        { value: 'Niger ', text: 'Niger ' },
        { value: 'Nigerija', text: 'Nigerija' },
        { value: 'Niu', text: 'Niu' },
        { value: 'Otok Norflok', text: 'Otok Norflok' },
        { value: 'Severni Marianski otoki', text: 'Severni Marianski otoki' },
        { value: 'Norveška', text: 'Norveška' },
        { value: 'Oman', text: 'Oman' },
        { value: 'Pakistan', text: 'Pakistan' },
        { value: 'Palau ', text: 'Palau ' },
        { value: 'Palestina', text: 'Palestina' },
        { value: 'Panama', text: 'Panama' },
        { value: 'Papua Nova Gvineja', text: 'Papua Nova Gvineja' },
        { value: 'Paragvaj', text: 'Paragvaj' },
        { value: 'Peru', text: 'Peru' },
        { value: 'Filipini', text: 'Filipini' },
        { value: 'Pitcairnovi otoki', text: 'Pitcairnovi otoki' },
        { value: 'Poljska', text: 'Poljska' },
        { value: 'Portugalska', text: 'Portugalska' },
        { value: 'Portoriko', text: 'Portoriko' },
        { value: 'Katar', text: 'Katar' },
        { value: 'Francoska skupnost Reunion', text: 'Francoska skupnost Reunion' },
        { value: 'Romunija', text: 'Romunija' },
        { value: 'Ruska federacija', text: 'Ruska federacija' },
        { value: 'Ruanda', text: 'Ruanda' },
        { value: 'Sveti Bartolomej', text: 'Sveti Bartolomej' },
        { value: 'Sveta Helena', text: 'Sveta Helena' },
        { value: 'Sveti Kits in Nevis', text: 'Sveti Kits in Nevis' },
        { value: 'Sveta Lucija', text: 'Sveta Lucija' },
        { value: 'Otok svetega Martina', text: 'Otok svetega Martina' },
        { value: 'Sveta Pierre in Miquelon', text: 'Sveta Pierre in Miquelon' },
        { value: 'Sveti Vincent in Grenadini', text: 'Sveti Vincent in Grenadini' },
        { value: 'Samoa', text: 'Samoa' },
        { value: 'San Marino', text: 'San Marino' },
        { value: 'Sao Tome in Principe', text: 'Sao Tome in Principe' },
        { value: 'Savdska Arabija', text: 'Savdska Arabija' },
        { value: 'Senegal', text: 'Senegal' },
        { value: 'Srbija', text: 'Srbija' },
        { value: 'Sejšeli', text: 'Sejšeli' },
        { value: 'Siera Leone', text: 'Siera Leone' },
        { value: 'Singapur', text: 'Singapur' },
        { value: 'Otok svetega.Martina (Nizozemska)', text: 'Otok svetega.Martina (Nizozemska)' },
        { value: 'Slovaška', text: 'Slovaška' },
        { value: 'Slovenija', text: 'Slovenija' },
        { value: 'Solomonovi otoki', text: 'Solomonovi otoki' },
        { value: 'Somalija', text: 'Somalija' },
        { value: 'Južna afrika', text: 'Južna afrika' },
        { value: 'Južna Georgia in Južni Sandwichevi otoki', text: 'Južna Georgia in Južni Sandwichevi otoki' },
        { value: 'Južni Sudan', text: 'Južni Sudan' },
        { value: 'Španija', text: 'Španija' },
        { value: 'Šri Lanka', text: 'Šri Lanka' },
        { value: 'Sudan', text: 'Sudan' },
        { value: 'Surinam', text: 'Surinam' },
        { value: 'Svalbard in Jan Majen ', text: 'Svalbard in Jan Majen ' },
        { value: 'Svazi', text: 'Svazi' },
        { value: 'Švedska', text: 'Švedska' },
        { value: 'Švica', text: 'Švica' },
        { value: 'Sirija', text: 'Sirija' },
        { value: 'Tajvan', text: 'Tajvan' },
        { value: 'Tadžikistan', text: 'Tadžikistan' },
        { value: 'Tanzanija', text: 'Tanzanija' },
        { value: 'Tajska', text: 'Tajska' },
        { value: 'Vzhodni Timor', text: 'Vzhodni Timor' },
        { value: 'Togo', text: 'Togo' },
        { value: 'Tokelau', text: 'Tokelau' },
        { value: 'Tonga', text: 'Tonga' },
        { value: 'Trinidad in Tobago', text: 'Trinidad in Tobago' },
        { value: 'Tunizija', text: 'Tunizija' },
        { value: 'Turčija', text: 'Turčija' },
        { value: 'Turkmenistan', text: 'Turkmenistan' },
        { value: 'Tirški in Kajkoški otoki', text: 'Tirški in Kajkoški otoki' },
        { value: 'Tuvalu', text: 'Tuvalu' },
        { value: 'Uganda', text: 'Uganda' },
        { value: 'Ukrajina', text: 'Ukrajina' },
        { value: 'Združeni Arabski Emirati', text: 'Združeni Arabski Emirati' },
        { value: 'Velika Britanija', text: 'Velika Britanija' },
        { value: 'Združene države Amerike', text: 'Združene države Amerike' },
        { value: 'ZDA zunanji otoki', text: 'ZDA zunanji otoki' },
        { value: 'Urugvaj', text: 'Urugvaj' },
        { value: 'Uzbekistan', text: 'Uzbekistan' },
        { value: 'Republika Vanuatu', text: 'Republika Vanuatu' },
        { value: 'Venezuela', text: 'Venezuela' },
        { value: 'Vietnam', text: 'Vietnam' },
        { value: 'Britanski Deviški otoki', text: 'Britanski Deviški otoki' },
        { value: 'Ameriški Deviški otoki', text: 'Ameriški Deviški otoki' },
        { value: 'Otočje Valis in Futuna', text: 'Otočje Valis in Futuna' },
        { value: 'Zahodna Sahara', text: 'Zahodna Sahara' },
        { value: 'Jemen', text: 'Jemen' },
        { value: 'Zambija', text: 'Zambija' },
        { value: 'Zimbabve', text: 'Zimbabve' },
      ],
      posts: [
      { value: 'Ankaran', text: 'Ankaran' },
      { value: 'Ajdovščina ', text: 'Ajdovščina ' },
      { value: 'Apače ', text: 'Apače ' },
      { value: 'Beltinci ', text: 'Beltinci ' },
      { value: 'Benedikt ', text: 'Benedikt ' },
      { value: 'Bistrica ob Sotli ', text: 'Bistrica ob Sotli ' },
      { value: 'Bled ', text: 'Bled ' },
      { value: 'Bloke ', text: 'Bloke ' },
      { value: 'Bohinj ', text: 'Bohinj ' },
      { value: 'Borovnica ', text: 'Borovnica ' },
      { value: 'Bovec ', text: 'Bovec ' },
      { value: 'Braslovče ', text: 'Braslovče ' },
      { value: 'Brda ', text: 'Brda ' },
      { value: 'Brezovica ', text: 'Brezovica ' },
      { value: 'Brežice ', text: 'Brežice ' },
      { value: 'Cankova ', text: 'Cankova ' },
      { value: 'Celje ', text: 'Celje ' },
      { value: 'Cerklje na Gorenjskem ', text: 'Cerklje na Gorenjskem ' },
      { value: 'Cerknica ', text: 'Cerknica ' },
      { value: 'Cerkno ', text: 'Cerkno ' },
      { value: 'Cerkvenjak ', text: 'Cerkvenjak ' },
      { value: 'Cirkulane ', text: 'Cirkulane ' },
      { value: 'Črenšovci ', text: 'Črenšovci ' },
      { value: 'Črna na Koroškem ', text: 'Črna na Koroškem ' },
      { value: 'Črnomelj ', text: 'Črnomelj ' },
      { value: 'Destrnik ', text: 'Destrnik ' },
      { value: 'Divača ', text: 'Divača ' },
      { value: 'Dobje ', text: 'Dobje ' },
      { value: 'Dobrepolje ', text: 'Dobrepolje ' },
      { value: 'Dobrna ', text: 'Dobrna ' },
      { value: 'Dobrova - Polhov Gradec ', text: 'Dobrova - Polhov Gradec ' },
      { value: 'Dobrovnik ', text: 'Dobrovnik ' },
      { value: 'Dol pri Ljubljani ', text: 'Dol pri Ljubljani ' },
      { value: 'Dolenjske Toplice ', text: 'Dolenjske Toplice ' },
      { value: 'Domžale ', text: 'Domžale ' },
      { value: 'Dornava ', text: 'Dornava ' },
      { value: 'Dravograd ', text: 'Dravograd ' },
      { value: 'Duplek ', text: 'Duplek ' },
      { value: 'Gorenja vas - Poljane ', text: 'Gorenja vas - Poljane ' },
      { value: 'Gorišnica ', text: 'Gorišnica ' },
      { value: 'Gorje ', text: 'Gorje ' },
      { value: 'Gornja Radgona ', text: 'Gornja Radgona ' },
      { value: 'Gornji Grad ', text: 'Gornji Grad ' },
      { value: 'Gornji Petrovci ', text: 'Gornji Petrovci ' },
      { value: 'Grad ', text: 'Grad ' },
      { value: 'Grosuplje ', text: 'Grosuplje ' },
      { value: 'Hajdina ', text: 'Hajdina ' },
      { value: 'Hoče - Slivnica ', text: 'Hoče - Slivnica ' },
      { value: 'Hodoš ', text: 'Hodoš ' },
      { value: 'Horjul ', text: 'Horjul ' },
      { value: 'Hrastnik ', text: 'Hrastnik ' },
      { value: 'Hrpelje - Kozina ', text: 'Hrpelje - Kozina ' },
      { value: 'Idrija ', text: 'Idrija ' },
      { value: 'Ig ', text: 'Ig ' },
      { value: 'Ilirska Bistrica ', text: 'Ilirska Bistrica ' },
      { value: 'Ivančna Gorica ', text: 'Ivančna Gorica ' },
      { value: 'Izola ', text: 'Izola ' },
      { value: 'Jesenice ', text: 'Jesenice ' },
      { value: 'Jezersko ', text: 'Jezersko ' },
      { value: 'Juršinci ', text: 'Juršinci ' },
      { value: 'Kamnik ', text: 'Kamnik ' },
      { value: 'Kanal ', text: 'Kanal ' },
      { value: 'Kidričevo ', text: 'Kidričevo ' },
      { value: 'Kobarid ', text: 'Kobarid ' },
      { value: 'Kobilje ', text: 'Kobilje ' },
      { value: 'Kočevje ', text: 'Kočevje ' },
      { value: 'Komen ', text: 'Komen ' },
      { value: 'Komenda ', text: 'Komenda ' },
      { value: 'Koper ', text: 'Koper ' },
      { value: 'Kostanjevica na Krki ', text: 'Kostanjevica na Krki ' },
      { value: 'Kostel ', text: 'Kostel ' },
      { value: 'Kozje ', text: 'Kozje ' },
      { value: 'Kranj ', text: 'Kranj ' },
      { value: 'Kranjska Gora ', text: 'Kranjska Gora ' },
      { value: 'Križevci ', text: 'Križevci ' },
      { value: 'Krško ', text: 'Krško ' },
      { value: 'Kungota ', text: 'Kungota ' },
      { value: 'Kuzma ', text: 'Kuzma ' },
      { value: 'Laško ', text: 'Laško ' },
      { value: 'Lenart ', text: 'Lenart ' },
      { value: 'Lendava ', text: 'Lendava ' },
      { value: 'Litija ', text: 'Litija ' },
      { value: 'Ljubljana ', text: 'Ljubljana ' },
      { value: 'Ljubno ', text: 'Ljubno ' },
      { value: 'Ljutomer ', text: 'Ljutomer ' },
      { value: 'Log - Dragomer ', text: 'Log - Dragomer ' },
      { value: 'Logatec ', text: 'Logatec ' },
      { value: 'Loška dolina ', text: 'Loška dolina ' },
      { value: 'Loški Potok ', text: 'Loški Potok ' },
      { value: 'Lovrenc na Pohorju ', text: 'Lovrenc na Pohorju ' },
      { value: 'Luče ', text: 'Luče ' },
      { value: 'Lukovica ', text: 'Lukovica ' },
      { value: 'Majšperk ', text: 'Majšperk ' },
      { value: 'Makole ', text: 'Makole ' },
      { value: 'Maribor ', text: 'Maribor ' },
      { value: 'Markovci ', text: 'Markovci ' },
      { value: 'Medvode ', text: 'Medvode ' },
      { value: 'Mengeš ', text: 'Mengeš ' },
      { value: 'Metlika ', text: 'Metlika ' },
      { value: 'Mežica ', text: 'Mežica ' },
      { value: 'Miklavž na Dravskem polju', text: 'Miklavž na Dravskem polju' },
      { value: 'Miren - Kostanjevica ', text: 'Miren - Kostanjevica ' },
      { value: 'Mirna ', text: 'Mirna ' },
      { value: 'Mirna Peč ', text: 'Mirna Peč ' },
      { value: 'Mislinja ', text: 'Mislinja ' },
      { value: 'Mokronog - Trebelno ', text: 'Mokronog - Trebelno ' },
      { value: 'Moravče ', text: 'Moravče ' },
      { value: 'Moravske Toplice ', text: 'Moravske Toplice ' },
      { value: 'Mozirje ', text: 'Mozirje ' },
      { value: 'Murska Sobota ', text: 'Murska Sobota ' },
      { value: 'Muta ', text: 'Muta ' },
      { value: 'Naklo ', text: 'Naklo ' },
      { value: 'Nazarje ', text: 'Nazarje ' },
      { value: 'Nova Gorica ', text: 'Nova Gorica ' },
      { value: 'Novo mesto ', text: 'Novo mesto ' },
      { value: 'Odranci ', text: 'Odranci ' },
      { value: 'Oplotnica ', text: 'Oplotnica ' },
      { value: 'Ormož ', text: 'Ormož ' },
      { value: 'Osilnica ', text: 'Osilnica ' },
      { value: 'Pesnica ', text: 'Pesnica ' },
      { value: 'Piran ', text: 'Piran ' },
      { value: 'Pivka ', text: 'Pivka ' },
      { value: 'Podčetrtek ', text: 'Podčetrtek ' },
      { value: 'Podlehnik ', text: 'Podlehnik ' },
      { value: 'Podvelka ', text: 'Podvelka ' },
      { value: 'Poljčane ', text: 'Poljčane ' },
      { value: 'Polzela ', text: 'Polzela ' },
      { value: 'Postojna ', text: 'Postojna ' },
      { value: 'Prebold ', text: 'Prebold ' },
      { value: 'Preddvor ', text: 'Preddvor ' },
      { value: 'Prevalje ', text: 'Prevalje ' },
      { value: 'Ptuj ', text: 'Ptuj ' },
      { value: 'Puconci ', text: 'Puconci ' },
      { value: 'Rače - Fram ', text: 'Rače - Fram ' },
      { value: 'Radeče ', text: 'Radeče ' },
      { value: 'Radenci ', text: 'Radenci ' },
      { value: 'Radlje ob Dravi ', text: 'Radlje ob Dravi ' },
      { value: 'Radovljica ', text: 'Radovljica ' },
      { value: 'Ravne na Koroškem ', text: 'Ravne na Koroškem ' },
      { value: 'Razkrižje ', text: 'Razkrižje ' },
      { value: 'Rečica ob Savinji ', text: 'Rečica ob Savinji ' },
      { value: 'Renče - Vogrsko ', text: 'Renče - Vogrsko ' },
      { value: 'Ribnica ', text: 'Ribnica ' },
      { value: 'Ribnica na Pohorju ', text: 'Ribnica na Pohorju ' },
      { value: 'Rogaška Slatina ', text: 'Rogaška Slatina ' },
      { value: 'Rogašovci ', text: 'Rogašovci ' },
      { value: 'Rogatec ', text: 'Rogatec ' },
      { value: 'Ruše ', text: 'Ruše ' },
      { value: 'Selnica ob Dravi ', text: 'Selnica ob Dravi ' },
      { value: 'Semič ', text: 'Semič ' },
      { value: 'Sevnica ', text: 'Sevnica ' },
      { value: 'Sežana ', text: 'Sežana ' },
      { value: 'Slovenj Gradec ', text: 'Slovenj Gradec ' },
      { value: 'Slovenska Bistrica ', text: 'Slovenska Bistrica ' },
      { value: 'Slovenske Konjice ', text: 'Slovenske Konjice ' },
      { value: 'Sodražica ', text: 'Sodražica ' },
      { value: 'Solčava ', text: 'Solčava ' },
      { value: 'Središče ob Dravi ', text: 'Središče ob Dravi ' },
      { value: 'Starše ', text: 'Starše ' },
      { value: 'Straža ', text: 'Straža ' },
      { value: 'Sv. Trojica v Slov. Goricah ', text: 'Sv. Trojica v Slov. Goricah ' },
      { value: 'Sveta Ana ', text: 'Sveta Ana ' },
      { value: 'Sveti Andraž v Slov. Goricah ', text: 'Sveti Andraž v Slov. Goricah ' },
      { value: 'Sveti Jurij ob Ščavnici ', text: 'Sveti Jurij ob Ščavnici ' },
      { value: 'Sveti Jurij v Slov. Goricah ', text: 'Sveti Jurij v Slov. Goricah ' },
      { value: 'Sveti Tomaž ', text: 'Sveti Tomaž ' },
      { value: 'Šalovci ', text: 'Šalovci ' },
      { value: 'Šempeter - Vrtojba ', text: 'Šempeter - Vrtojba ' },
      { value: 'Šenčur ', text: 'Šenčur ' },
      { value: 'Šentilj ', text: 'Šentilj ' },
      { value: 'Šentjernej ', text: 'Šentjernej ' },
      { value: 'Šentjur pri Celju ', text: 'Šentjur pri Celju ' },
      { value: 'Šentrupert ', text: 'Šentrupert ' },
      { value: 'Škocjan ', text: 'Škocjan ' },
      { value: 'Škofja Loka ', text: 'Škofja Loka ' },
      { value: 'Škofljica ', text: 'Škofljica ' },
      { value: 'Šmarje pri Jelšah ', text: 'Šmarje pri Jelšah ' },
      { value: 'Šmarješke Toplice ', text: 'Šmarješke Toplice ' },
      { value: 'Šmartno ob Paki ', text: 'Šmartno ob Paki ' },
      { value: 'Šmartno pri Litiji ', text: 'Šmartno pri Litiji ' },
      { value: 'Šoštanj ', text: 'Šoštanj ' },
      { value: 'Štore ', text: 'Štore ' },
      { value: 'Tabor ', text: 'Tabor ' },
      { value: 'Tišina ', text: 'Tišina ' },
      { value: 'Tolmin ', text: 'Tolmin ' },
      { value: 'Trbovlje ', text: 'Trbovlje ' },
      { value: 'Trebnje ', text: 'Trebnje ' },
      { value: 'Trnovska vas ', text: 'Trnovska vas ' },
      { value: 'Trzin ', text: 'Trzin ' },
      { value: 'Tržič ', text: 'Tržič ' },
      { value: 'Turnišče ', text: 'Turnišče ' },
      { value: 'Velenje ', text: 'Velenje ' },
      { value: 'Velika Polana ', text: 'Velika Polana ' },
      { value: 'Velike Lašče ', text: 'Velike Lašče ' },
      { value: 'Veržej ', text: 'Veržej ' },
      { value: 'Videm ', text: 'Videm ' },
      { value: 'Vipava ', text: 'Vipava ' },
      { value: 'Vitanje ', text: 'Vitanje ' },
      { value: 'Vodice ', text: 'Vodice ' },
      { value: 'Vojnik ', text: 'Vojnik ' },
      { value: 'Vransko ', text: 'Vransko ' },
      { value: 'Vrhnika ', text: 'Vrhnika ' },
      { value: 'Vuzenica ', text: 'Vuzenica ' },
      { value: 'Zagorje ob Savi ', text: 'Zagorje ob Savi ' },
      { value: 'Zavrč ', text: 'Zavrč ' },
      { value: 'Zreče ', text: 'Zreče ' },
      { value: 'Žalec ', text: 'Žalec ' },
      { value: 'Železniki ', text: 'Železniki ' },
      { value: 'Žetale ', text: 'Žetale ' },
      { value: 'Žiri ', text: 'Žiri ' },
      { value: 'Žirovnica ', text: 'Žirovnica ' },
      { value: 'Žužemberk ', text: 'Žužemberk ' },
      ],
    }
  },
  components: {
  },
  methods: {
    onSubmit() {
      this.$router.push({name: 'login'});
    },
    goBack() {
      this.$router.push({name: 'login'});
    },
    onReset() {
    },
    goHome() {
      this.$router.push({name: 'home'});
    },
    saveProfile() {
      this.$snotify.async('Saved', 'saved', () => new Promise((resolve, reject) =>
        resolve({
          config: {
            closeOnClick: true,
            timeout: 2000,
          },
        })
      ));
    },
  },
})
export default class Profile extends Vue {}
</script>

<style lang="scss">
  #logintext {
    padding: 0.3em;
  }
  .backBtn {
    position: absolute;
    left: 0;
    box-sizing: border-box;
  }
  .forgotBtn {
    position: absolute;
    right: 0;
    box-sizing: border-box;
  }
</style>
